### ISSUE TITLE
Sending status: Exception Unable to execute the request - 'Core' object has no attribute 'llm'

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [AmberSahdev/Open-Interface#1]
I get 'Sending status: Exception Unable to execute the request - 'Core' object has no attribute 'llm'' when I try to type any command

**Comment by AmberSahdev** [comment]
Check out the [Setup section](https://github.com/AmberSahdev/Open-Interface?tab=readme-ov-file#setup-%EF%B8%8F). You're likely just missing the OpenAI key you have to set manually. Also be sure to restart the app after that.

**Comment by AmberSahdev** [comment]
Added better error reporting for this.
