### ISSUE TITLE
issue api key

### ISSUE THREAD

**Issue by doncapote** [AmberSahdev/Open-Interface#13]
hello already place my api key provide for open ai but it already have error
![ww](https://github.com/user-attachments/assets/404f1008-cc14-4cae-8847-2b75b1a8b6e8)

**Comment by AmberSahdev** [comment]
aah yeah lemme upload some new binaries by the weekend to resolve this

**Comment by AmberSahdev** [comment]
0.6.0 released now and has support for newer models.
