### ISSUE TITLE
'Core' object has no attribute 'llm'

### ISSUE THREAD

**Issue by EkaterinaRubel** [AmberSahdev/Open-Interface#2]
hello
I have the problem 'Core' object has no attribute 'llm'

my env macOS Apple M1 Max
browser Safari
<img width="1209" alt="Screenshot 2024-03-25 at 20 25 29" src="https://github.com/AmberSahdev/Open-Interface/assets/130956760/eec10a32-e341-48e1-b4eb-5e697337b246">

**Comment by AmberSahdev** [comment]
Did you restart the app after setting the OpenAI API key? 

I'll add better error handling and messages here.

**Comment by AmberSahdev** [comment]
Added a better error message in the new release (0.5.0) prompting user to restart the app after setting the API key.
