### ISSUE TITLE
Error Launching App with Local LLM on WSL Using Ollama

### ISSUE THREAD

**Issue by Hammad-Mir** [AmberSahdev/Open-Interface#20]
I attempted to set up using a local LLM in WSL using Ollama. After entering the configuration details for the local model and restarting the app, I encountered the following error. Now, the app won’t open, and I’m unable to make any further changes.

Traceback (most recent call last):
  File "app\app.py", line 74, in <module>
  File "app\app.py", line 39, in __init__
  File "C:\Users\hamma\AppData\Local\Temp\_MEI1082882\core.py", line 22, in __init__
    self.llm = LLM()
               ^^^^^
  File "C:\Users\hamma\AppData\Local\Temp\_MEI1082882\llm.py", line 59, in __init__
    self.model = ModelFactory.create_model(self.model_name, base_url, api_key, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hamma\AppData\Local\Temp\_MEI1082882\models\factory.py", line 13, in create_model
    raise ValueError(f'Unsupported model type {model_name}. Create entry in app/models/')
ValueError: Unsupported model type llama3.1. Create entry in app/models/

**Comment by ludvigpujsek** [comment]
I am encountering the same issue trying to run _llava_ through ollama. I'd like to add that deleting the TEMP_MEI[...]-directory in appdata (and then overwriting the executable with a new one, just in case) for some reason doesn't fix the issue. I've looked througth %appdata%/Local, LocalLow and Roaming, and none of them seem to contain any trace that some sort of persistent configuration might have been left by the program.

**Comment by ludvigpujsek** [comment]
After digging through the temporary file generated and following the python functions back to where the settings are read:
The file that causes the program to no longer launch properly is a settings.json saved in _%userprofile%/.open-interface_ or (most probably) _c:/Users/<your_user>/.open-interface_. Remember to replace "/" with "\" if copy pasting path into file explorer in Windows. Deleting settings.json will make the program reset the selected model and thus allow it to launch.

**Comment by Hammad-Mir** [comment]
Thanks! This resolved the app running issue. Any success with running the app with Ollama?

**Comment by ludvigpujsek** [comment]
> Thanks! This resolved the app running issue. Any success with running the app with Ollama?

No such luck - I have an exam in 2 days, so I probably won't be able to get back to this 'til after then.

**Comment by AmberSahdev** [comment]
Ope fixed it for MacOS M Series in 0.6.1. Will compile the Linux/Windows binaries later in the weekend I don't have my desktop right now. 

Thanks for the analysis @ludvigpujsek appreciate it!

**Comment by AmberSahdev** [comment]
Released another version with better error reporting if you're still facing issues with startup with custom models 
https://github.com/AmberSahdev/Open-Interface/releases/tag/0.7.0
