### ISSUE TITLE
App startup failed with MacBook Air 2024(m3)

### ISSUE THREAD

**Issue by brucevoin** [AmberSahdev/Open-Interface#24]

**Comment by terrellbm** [comment]
App startup also failed with Apple M2 Pro 2023

Using `open -a "/Applications/Open Interface.app" ` caused the process to appear in activity monitor, but the process disappeared after a couple of seconds

**Comment by quinnpertuit** [comment]
`open -a` works on my m3 w/ rosetta installed. try running `arch -x86_64 open -a "/Applications/Open Interface.app"`

**Comment by ptrkstr** [comment]
Specs:
- Apple M1 Max
- 15.0.1 (24A348)

Tried opening it via:
- Applications folder
- `open -a "/Applications/Open Interface.app"`
- `arch -x86_64 open -a "/Applications/Open Interface.app"`
- Rosetta is installed

The app appears in the task bar for a second then disappears.

**Comment by AmberSahdev** [comment]
Added better error handling during startup in the new version that should better address and report these issues. Check it out! 
https://github.com/AmberSahdev/Open-Interface/releases/tag/0.7.0
